### ISSUE TITLE
imgs & imgs_org and imgs & normals and data['images'] & data['untrans-images']

### ISSUE THREAD

**Issue by leyuan-sun** [ArashJavan/DeepLIO#14]
https://github.com/ArashJavan/DeepLIO/blob/master/deeplio/models/misc.py#:~:text=if%20has_imgs%3A,untrans-images%27%5D.to(self.device))

What is the difference or meaning of these variables? Thanks ahead!

**Comment by leyuan-sun** [comment]
https://github.com/ArashJavan/DeepLIO/blob/master/deeplio/models/misc.py#:~:text=xyz_imgs%20%3D%20imgs%5B%3A%2C%20%3A%2C%20%3A%2C%200,imgs%5B%3A%2C%20%3A%2C%20%3A%2C%203%3A%5D.contiguous()

Also, what do xyz_imgs and normals_imgs mean?

**Comment by leyuan-sun** [comment]
~~In your paper Figure1, the middle image is rendered from spherical projection, could u plz show me where is the implementation of this part in the code ?~~

I found it in kitty.py

**Comment by ArashJavan** [comment]
@rginjapan xyz-image is basically an image with three xyz-coordinate channels. Normal-image is also a three-channel (nx-ny-nz) image with the normalized vector directions of the normals at each pixel. Hope it is clear now!

**Comment by leyuan-sun** [comment]
Thanks for your reply, could u plz answer my latest issue?
