### ISSUE TITLE
RMSE result

### ISSUE THREAD

**Issue by tym2103** [ArashJavan/DeepLIO#5]
Can you show the train and test seq RMSE result like follow
![Snipaste_2020-11-03_20-02-27](https://user-images.githubusercontent.com/25846732/97982977-86cf3000-1e0f-11eb-9ee0-b2fcdf2909bd.png)
![Snipaste_2020-11-03_20-02-21](https://user-images.githubusercontent.com/25846732/97982991-89318a00-1e0f-11eb-96ef-9f7738effd5e.png)

**Comment by ArashJavan** [comment]
@tym2103 I will upload a pretrained network and all results soon.

**Comment by tym2103** [comment]
thank your
