### ISSUE TITLE
About imu mean and std

### ISSUE THREAD

**Issue by tym2103** [ArashJavan/DeepLIO#6]
What sequences does it include，00-08 or 00-10

**Comment by ArashJavan** [comment]
The mean and std for imu and lidars are calculated from seq. 00-08, which were used as training datasets in this project.

**Comment by tym2103** [comment]
OK，and the mean and std about imu in config.yaml and readme.md are different
which one you use?

**Comment by ArashJavan** [comment]
I use the config.yaml values, README is partly outdated and is just a showcase. I will update it soon.

**Comment by tym2103** [comment]
I both try  two value adout mean and std
In my method to solve odometry problem, the outdated value can get better result
I  use 09-10 as testset as well
Do you remember  the formula to get outdated value
Thanks a lot

**Comment by ArashJavan** [comment]
The mean and std are calculated using this [script](https://github.com/ArashJavan/DeepLIO/blob/master/scripts/mean_std_dataset.py).

**Comment by tym2103** [comment]
the script's result is config.yaml values.
But I want to know how to get outdated result which from README.
sorry to trouble you again

**Comment by ArashJavan** [comment]
I just checked the history of git! 
The mean/std you are looking for are added first at  14.05.2020 with the commit comment "Adding pointseg" and this commit.
1df26843e7a9f7f333fff565f53ef35c0adc4f52

Just check out this commit and run the script at that version, you may get the same "outdated" results!

good luck 
Arash

**Comment by tym2103** [comment]
I find in this version the mean and std of imu are  "outdated" results in config.xml
[https://github.com/ArashJavan/DeepLIO/tree/pre_redesign](url)
But I can only get the "newest" mean and std data as result.
Do you still remember this version?

**Comment by tym2103** [comment]
I find in this version you add "outdated" imu mean and std in config,yaml
ad2fadd9bfbd6bbfb26434489701384ae07e97ed
But I use this version to get the "newest" results
Do you still remember this version?
thank you

**Comment by ArashJavan** [comment]
> _Do you still remember this version?_
I am not sure what you mean by that! But anyway run the script of that version and see if you get the results as in README. But I do not really remember the configuration for those values in README.

**Comment by tym2103** [comment]
I know how to get "outdated" result, in that version's config.yaml, trainset is 00-07 rather than 00-08. I forget to modify the trainset value!!!
sorry for trouble you so many times
Thanks again for your answers
^-^
