### ISSUE TITLE
Did you publish an article about this project?

### ISSUE THREAD

**Issue by tym2103** [ArashJavan/DeepLIO#7]
Your project has inspired me so much that I want to quote your paper!!!

**Comment by ArashJavan** [comment]
@tym2103 sorry for the delayed reply. I am really glad to hear that DeepLIO could help/inspire you :) . 
Yes, the project will be published soon - at least I hope :).
But nevertheless, if you can not wait till then, you can also quote the git-repo.

Good luck with your project and happy to hear from you and your projects soon!

**Comment by ArashJavan** [comment]
@tym2103 ok, the paper is published now [here](https://www.isprs-ann-photogramm-remote-sens-spatial-inf-sci.net/V-1-2021/47/2021/)

**Comment by rginjapan** [comment]
@ArashJavan I have already read your nice paper, just want to know, did you try to evaluate the uncertainty in your loss function (33).

**Comment by ArashJavan** [comment]
@rginjapan I am very pleased. Well, that's a really good point! We have some thoughts about it, but for now, we are expanding deeplio to use raw point clouds. But expressing uncertainty on the estimations - e.g. using monte carlo dropout, is also in the pipeline ;)
